// Composite "remix brief" — the portable artifact a remix produces.
// Fuses a UI design language + a palette + an art-style recipe + a composition
// into one document that is BOTH the human "Copy" payload and the agent-fetchable
// artifact (served by /studio/BRIEF.md). The downstream agent fills the art and
// builds the screen; Katagami never generates — it specifies.

export interface RemixSlot {
  key: string;
  subject_hint: string;
  aspect: string;
}

export interface RemixComposition {
  key: string;
  name: string;
  description?: string;
  image_slots: RemixSlot[];
}

export interface RemixBriefInput {
  language: {
    name: string;
    slug?: string;
    tokens?: Record<string, unknown> | null;
    designMdUrl?: string;
  };
  palette: {
    name: string;
    roles: Record<string, string>;
  };
  artStyle: {
    name: string;
    medium: string;
    promptTemplate: string;
    negativePrompt?: string;
    slotRecipes?: Record<string, string>;
    referenceUrls?: string[];
  };
  composition: RemixComposition;
}

/** Render the palette roles as a compact, prompt-friendly string. */
export function paletteToPromptString(roles: Record<string, string>): string {
  return Object.entries(roles)
    .filter(([, v]) => typeof v === "string" && v)
    .map(([k, v]) => `${k} ${v}`)
    .join(", ");
}

/** Fill an art-style template's {subject} and {palette} holes for one slot. */
export function resolveSlotPrompt(
  template: string,
  subject: string,
  roles: Record<string, string>,
): string {
  return template
    .replace(/\{subject\}/g, subject)
    .replace(/\{palette\}/g, paletteToPromptString(roles));
}

function slotSubject(slot: RemixSlot, slotRecipes?: Record<string, string>): string {
  if (slotRecipes) {
    // exact key, then family (feature-1 -> feature, testimonial-avatar-1 -> avatar)
    if (slotRecipes[slot.key]) return `${slotRecipes[slot.key]}`;
    const family = slot.key.replace(/-?\d+$/, "").replace(/^testimonial-/, "");
    if (slotRecipes[family]) return slotRecipes[family];
  }
  return slot.subject_hint;
}

export function buildRemixBrief(input: RemixBriefInput): string {
  const { language, palette, artStyle, composition } = input;
  const roles = palette.roles ?? {};

  const slotLines = composition.image_slots.map((slot) => {
    const subject = slotSubject(slot, artStyle.slotRecipes);
    const prompt = resolveSlotPrompt(artStyle.promptTemplate, subject, roles);
    return [
      `  - key: ${slot.key}`,
      `    subject: ${JSON.stringify(subject)}`,
      `    aspect: ${JSON.stringify(slot.aspect)}`,
      `    prompt: ${JSON.stringify(prompt)}`,
    ].join("\n");
  });

  const frontMatter = [
    "---",
    "katagami_brief: v1",
    `ui: { name: ${JSON.stringify(language.name)}, slug: ${JSON.stringify(language.slug ?? "")} }`,
    `palette: { name: ${JSON.stringify(palette.name)} }`,
    `art_style: { name: ${JSON.stringify(artStyle.name)}, medium: ${JSON.stringify(artStyle.medium)} }`,
    `composition: ${JSON.stringify(composition.key)}`,
    "palette_tokens:",
    ...Object.entries(roles).map(([k, v]) => `  ${k}: ${JSON.stringify(v)}`),
    "slots:",
    ...slotLines,
    "---",
  ].join("\n");

  const refs =
    artStyle.referenceUrls && artStyle.referenceUrls.length
      ? artStyle.referenceUrls.map((u) => `- ${u}`).join("\n")
      : "_(none attached)_";

  const body = `
# Remix brief — ${composition.name}

**${language.name}** (UI) · **${palette.name}** (palette) · **${artStyle.name}** (art style, ${artStyle.medium})

## How to build this screen
1. Apply the UI design language${language.designMdUrl ? ` — see DESIGN.md: ${language.designMdUrl}` : ""}.
2. Theme it with the palette tokens above (map roles to your color variables).
3. For each slot below, **generate** an image with the resolved prompt + attach the
   reference images as style references, then place it in the named slot.
4. Honor the art style's negative prompt and keep one coherent look across slots.

## Art style recipe
- **Prompt template:** \`${artStyle.promptTemplate}\`
${artStyle.negativePrompt ? `- **Negative prompt:** \`${artStyle.negativePrompt}\`` : ""}

## Reference images (match this look)
${refs}

> Generated by Katagami. Katagami specifies the remix; your agent generates the art.
`;

  return `${frontMatter}\n${body}`;
}
